WebApplication5/Controllers/ClaimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication5.Controllers
{
    public class ClaimController : Controller
    {
        // GET: Claim
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication5/Controllers/EditClaimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication5.Controllers
{
    public class EditClaimController : Controller
    {
        // GET: EditClaim
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication5/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication5.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApplication5/Controllers/NewClaimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication5.Controllers
{
    public class NewClaimController : Controller
    {
        // GET: NewClaim
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication5/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication5.Controllers
{
    public class SearchController : Controller
    {
        // GET: Search
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication5/Controllers/SemanticUIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication5.Controllers
{
    public class SemanticUIController : Controller
    {
        //
        // GET: /SemanticUI/

        public ActionResult Index()
        {
            return View();
        }

    }
}

WebApplication5/Controllers/TableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication5.Controllers
{
    public class TableController : Controller
    {
        // GET: Table
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication5/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication5.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication5/Views/Claim/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout_Semantic.cshtml"; 
}
<div class="ui page grid overview segment">
    <div class="ui two wide column"></div>
    <div class="twelve wide column">
        <div class="ui four column center aligned stackable divided grid">
            <div class="column">
                <div class="ui icon header">
                    <i class="circular mail grey link icon"></i>
                </div>
                <p></p>
                <p><a class="ui red right labeled icon button" href="#">Mail<i class="right long arrow icon"></i></a></p>
            </div>
            <div class="column">
                <div class="ui icon header">
                    <i class="circular grey suitcase icon"></i>
                </div>
                <p></p>
                <p><a class="ui red right labeled icon button" href="@Url.Action("Index", "Table")">Claims<i class="arrow long right icon"></i></a></p>
            </div>
            <div class="column">
                <div class="ui icon header">
                    <i class="circular user grey link icon"></i>
                </div>
                <p></p>
                <p><a class="ui red right labeled icon button" href="@Url.Action("Index","User")">Users<i class="right long arrow icon"></i></a></p>
            </div>
            <div class="column">
                <div class="ui icon header">
                    <i class="circular id card grey link icon"></i>
                </div>
                <p></p>
                <p><a class="ui red right labeled icon button" href="@Url.Action("Index","NewClaim")">Claim<i class="right long arrow icon"></i></a></p>
            </div>
        </div>
    </div>
</div>

WebApplication5/Views/EditClaim/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout_Semantic.cshtml";
}
<div class="ui page grid stackable relaxed feature segment">
    <div class="row">
        <div class="sixteen wide column">
            <form class="ui form">
                <h4 class="ui dividing header">Claim Information</h4>
                <div class="four fields">
                    <div class="field">
                        <label>Order No</label>
                        <div class="field">
                            <input type="text" name="policyNo" placeholder="Policy No" value="test">
                        </div>
                    </div>
                    <div class="field">
                        <label>Claim No</label>
                        <div class="field">
                            <div class="field">
                                <input type="text" name="shipping[first-name]" placeholder="Claim No">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="field">
                    <label >Policy</label>
                    <div class="four fields">
                    
                        <div class="field">
                            <input type="text" name="policyHolder" placeholder="Policy Holder">
                        </div>
                        <div class="field">
                            <input type="text" name="policyHolderTitle" placeholder="Policy Holder Title">
                        </div>
                        <div class="field">
                            <input type="text" name="policyHolderInitials" placeholder="Policy Holder Initials">
                        </div>
                        <div class="field">
                            <input type="text" name="policyHolderSurname" placeholder="Policy Holder Surname">
                        </div>
                    </div>
                </div>
                <div class="field">
                    <label>Address</label>
                    <div class="four fields">
                        <div class="field">
                            <input type="text" name="Street[address]" placeholder="Street Address">
                        </div>
                        <div class="field">
                            <input type="text" name="Street[address-2]" placeholder="Suburb">
                        </div>
                        <div class="field">
                            <input type="text" name="Streeet[address-2]" placeholder="City/Town">
                        </div>
                        <div class="field">
                            <input type="text" name="Streeet[address-2]" placeholder="Postal Code">
                        </div>
                    </div>
                </div>
                <div class="field">
                    <label>Contact</label>
                    <div class="four fields">
                        <div class="field">
                            <input type="text" name="CellNo" placeholder="Cell No">
                        </div>
                        <div class="field">
                            <input type="text" name="HomeNo" placeholder="Home No">
                        </div>
                        <div class="field">
                            <input type="text" name="Business No" placeholder="Business No">
                        </div>
                        <div class="field">
                            <input type="text" name="Email" placeholder="Email Address">
                        </div>
                    </div>
                </div>
                <div class="four fields">
                    <div class="field">
                        <label>Date Of Loss</label>
                        <input type ="date" name ="dateOfLoss" placeholer="Date of Loss"/>
                    </div>
                    <div class="field">
                        <label>Sum Insured</label>
                        <input type="text" name ="sumInsured" placeholder="Sum Insured"/>
                    </div>
                    <div class="field">
                        <label>Is Body Corperate</label>
                        <div class="ui fitted slider checkbox">
                            <input type="checkbox"> <label></label>
                        </div>
                    </div>
                </div>
                <h4 class="ui dividing header">Progress</h4>
                <div class="field">
                    <label>Fogi</label>
                </div>
                <div class="field">
                    <label>Izinga</label>
                    
                </div>
                <div class="ui teal progress" data-percent="74" id="example1">
                    <div class="bar"></div>
                    <div class="label">74% Funded</div>
                </div>
                
                @*<div class="three fields">
                    <div class="field">
                        <label>Claim Progress</label>
                        <input type="text" name="replacementExcess" placeholder="Replacement Excess" />
                    </div>
                    <div class="field">
                        <label>Repair Excess</label>
                        <input type="text" name="repairExcess" placeholder="Repair Excess" />
                    </div>
                    <div class="field">
                        <label>Resultant Excess</label>
                        <input type="text" name="resultantExcess" placeholder="Resultant Excess" />
                    </div>
                </div>
                <h4 class="ui dividing header">Excess</h4>
                <div class="three fields">
                    <div class="field">
                        <label>Replacement Excess</label>
                        <input type="text" name="replacementExcess" placeholder="Replacement Excess"/>    
                    </div>
                    <div class="field">
                        <label>Repair Excess</label>
                        <input type="text" name="repairExcess" placeholder="Repair Excess" />
                    </div>
                    <div class="field">
                        <label>Resultant Excess</label>
                        <input type="text" name="resultantExcess" placeholder="Resultant Excess" />
                    </div>
                </div>
                <div class="field">
                    <label>Head Office</label>
                    <select class="ui fluid dropdown">
                        <option value="VA">ABSA IDirect</option>
                        <option value="WA">ABACUS</option>
                        <option value="WV">Kwikot</option>
                        <option value="WI">Momentum</option>
                        <option value="WY">PSG</option>
                    </select>
                </div>
                <div class="field">
                    <label>Branch</label>
                    <select class="ui fluid dropdown">
                        <option value="VA">ABSA IDirect</option>
                    </select>
                </div>
                <div class="field">
                    <label>Advisor</label>
                    <select class="ui fluid dropdown">
                        <option value="VA">[Auto Select Advisor]</option>
                    </select>
                </div>
                <div class="field">
                    <label>Policy Type</label>
                    <select class="ui fluid dropdown">
                        <option value="VA">[Auto Select Policy]</option>
                    </select>
                </div>
                <h4 class="ui dividing header">Damages</h4>
                
                <div class="ui segment">
                    <div class="field">
                        <div class="ten wide field">
                            <Label>Plumbing Failure</Label>
                            <textarea placeholder="Plumbing Failure"></textarea>    
                        </div>
                    </div>
                </div>
                <div class="ui segment">
                    <div class="field">
                        <div class="ui slider checkbox">
                            <input type="checkbox" name="gift" tabindex="0" class="hidden">
                            <label>Do not include a receipt in the package</label>
                        </div>
                    </div>
                </div>
                <div class="ui green button" tabindex="0">Submit</div>*@
            </form>
        </div>
    </div>
</div>
<script type='text/javascript'>

    $(document).ready(function () {

        $('#example1').progress({
            percent: 74
        });
        
    });

</script>

WebApplication5/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication5/Views/Home/Index.cshtml
@{
    //Layout = "~/Views/Shared/_Layout_Semantic.cshtml"; 
    Layout = "";
}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/semantic")
    @Styles.Render("~/Styles/Login.css")

</head>
<body>
<div class="ui middle aligned center aligned grid">
    <div class="column">
        <img src="~/Content/Images/Digicall_Solutions_Logo.jpg" style="width: 100%; height: 100%"/>
        <h2 class="ui header">
            <div class="content">
                Log-in to your account
            </div>
        </h2>
        <form action="@Url.Action("Index", "Claim")" method="get" class="ui form">
            <div class="ui stacked secondary segment">
                <div class="field">
                    <div class="ui left icon input">
                        <i class="user icon"></i>
                        <input type="text" name="email" placeholder="E-mail address">
                    </div>
                </div>
                <div class="field">
                    <div class="ui left icon input">
                        <i class="lock icon"></i>
                        <input type="password" name="password" placeholder="Password">
                    </div>
                </div>
                <div class="ui fluid large red submit button">Login</div>
            </div>

            <div class="ui error message"></div>

        </form>

        <div class="ui message">
            New to us? <a href="">Register</a>
        </div>
    </div>
</div>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/semantic")
@*@RenderSection("scripts", required: false)*@
    
    <script>

        $(document).ready(function () {

            $('.ui.form')
                    .form({
                        fields: {
                            email: {
                                identifier: 'email',
                                rules: [
                                    {
                                        type: 'empty',
                                        prompt: 'Please Enter a Valid Email'
                                    }
                                ]
                            },
                            password: {
                                identifier: 'password',
                                rules: [
                                    {
                                        type: 'minCount[6]',
                                        prompt: 'Please Enter a Valid Password'
                                    }
                                ]
                            }
                        }
                    })
                ;
        
        });
    </script>
}
</body>
</html>

WebApplication5/Views/NewClaim/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout_Semantic.cshtml"; ;
}

<div class="ui page grid stackable relaxed feature segment">
    <div class="row">
        <div class="sixteen wide column">
            <form class="ui form">
                <h4 class="ui dividing header">Claim Information</h4>
                <div class="field">
                    <label>Head Office</label>
                    <select class="ui fluid dropdown">
                        <option value="VA">ABSA IDirect</option>
                        <option value="WA">ABACUS</option>
                        <option value="WV">Kwikot</option>
                        <option value="WI">Momentum</option>
                        <option value="WY">PSG</option>
                    </select>
                </div>
                <div class="field">
                    <label>Branch</label>
                    <select class="ui fluid dropdown">
                        <option value="VA">ABSA IDirect</option>
                    </select>
                </div>
                <div class="field">
                    <label>Advisor</label>
                    <select class="ui fluid dropdown">
                        <option value="VA">[Auto Select Advisor]</option>
                    </select>
                </div>
            <div class="field">
                <label>Policy Type</label>
                <select class="ui fluid dropdown">
                    <option value="VA">[Auto Select Policy]</option>
                </select>
            </div>
            <div class="four fields">
                <div class="field">
                    <label>Policy No</label>
                    <div class="field">
                        <input type="text" name="policyNo" placeholder="Policy No">
                    </div>
                </div>
                <div class="field">
                    <label>Claim No</label>
                    <div class="field">
                        <div class="field">
                            <input type="text" name="shipping[first-name]" placeholder="Claim No">
                        </div>
                    </div>
                 </div>
            </div>
             <div class="field">
                <label >Policy</label>
            <div class="four fields">
                    
                <div class="field">
                    <input type="text" name="policyHolder" placeholder="Policy Holder">
                </div>
                <div class="field">
                    <input type="text" name="policyHolderTitle" placeholder="Policy Holder Title">
                </div>
                <div class="field">
                    <input type="text" name="policyHolderInitials" placeholder="Policy Holder Initials">
                </div>
                <div class="field">
                    <input type="text" name="policyHolderSurname" placeholder="Policy Holder Surname">
                </div>
               </div>
            </div>
            <div class="field">
                <label>Address</label>
                <div class="four fields">
                    <div class="field">
                        <input type="text" name="Street[address]" placeholder="Street Address">
                    </div>
                    <div class="field">
                        <input type="text" name="Street[address-2]" placeholder="Suburb">
                    </div>
                    <div class="field">
                        <input type="text" name="Streeet[address-2]" placeholder="City/Town">
                    </div>
                    <div class="field">
                        <input type="text" name="Streeet[address-2]" placeholder="Postal Code">
                    </div>
                </div>
            </div>
            <div class="field">
                <label>Contact</label>
                <div class="four fields">
                    <div class="field">
                        <input type="text" name="CellNo" placeholder="Cell No">
                    </div>
                    <div class="field">
                        <input type="text" name="HomeNo" placeholder="Home No">
                    </div>
                    <div class="field">
                        <input type="text" name="Business No" placeholder="Business No">
                    </div>
                    <div class="field">
                        <input type="text" name="Email" placeholder="Email Address">
                    </div>
                </div>
            </div>
                <div class="four fields">
                    <div class="field">
                        <label>Date Of Loss</label>
                        <input type ="date" name ="dateOfLoss" placeholer="Date of Loss"/>
                    </div>
                    <div class="field">
                        <label>Sum Insured</label>
                        <input type="text" name ="sumInsured" placeholder="Sum Insured"/>
                    </div>
                    <div class="field">
                        <label>Is Body Corperate</label>
                        <div class="ui fitted slider checkbox">
                            <input type="checkbox"> <label></label>
                        </div>
                    </div>
                </div>
                <h4 class="ui dividing header">Excess</h4>
            <div class="three fields">
                <div class="field">
                    <label>Replacement Excess</label>
                    <input type="text" name="replacementExcess" placeholder="Replacement Excess"/>    
                </div>
                <div class="field">
                    <label>Repair Excess</label>
                    <input type="text" name="repairExcess" placeholder="Repair Excess" />
                </div>
                <div class="field">
                    <label>Resultant Excess</label>
                    <input type="text" name="resultantExcess" placeholder="Resultant Excess" />
                </div>
            </div>
                <h4 class="ui dividing header">Damages</h4>
                
                <div class="ui segment">
                    <div class="field">
                        <div class="ten wide field">
                            <Label>Plumbing Failure</Label>
                            <textarea placeholder="Plumbing Failure"></textarea>    
                        </div>
                    </div>
                </div>
                <div class="ui segment">
                    <div class="field">
                        <div class="ui slider checkbox">
                            <input type="checkbox" name="gift" tabindex="0" class="hidden">
                            <label>Do not include a receipt in the package</label>
                        </div>
                    </div>
                </div>
            <div class="ui green button" tabindex="0">Submit</div>
          </form>
        </div>
    </div>
</div>

WebApplication5/Views/Search/Index.cshtml
@model dynamic

@{
    Layout = "~/Views/Shared/_Layout_Semantic.cshtml";
}
<div class="ui page grid stackable relaxed segment">
    <div class="row">
        <div class="sixteen wide column">
            <form class="ui form">
                <h4 class="ui dividing header">Search Criteria</h4>
                <div class="four fields">
                    <div class="field">
                        <label></label>
                        <select class="ui fluid dropdown">
                            <option value="claim">Claim No</option>
                            <option value="policy">Policy No</option>
                            <option value="callcenter">Call Center</option>
                            <option value="policyNumber">Policy Number</option>
                            <option value="caseno">Case No</option>
                        </select>
                    </div>
                    <div class="field">
                        <label></label>
                        <input type="text" placeholder="Search"/>
                    </div>
                    <div class="field">
                        <label></label>
                        <div class="ui grey button" tabindex="0"><i class="ui search icon"></i>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
        <div class="row">
            <div class="sixteen wide column">
                <table class="ui celled table">
                    <thead>
                    <tr>
                        <th>Order No</th>
                        <th>Claim No</th>
                        <th>Call Reference No</th>
                        <th>Policy No</th>
                        <th>Policy Holder</th>
                        <th>Address</th>
                        <th>City</th>
                        <th>Date Created</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>
                            <div class="ui red ribbon label"><a href="@Url.Action("Index","EditClaim")">202164</a></div>
                        </td>
                        <td>457575</td>
                        <td>31657</td>
                        <td>5474</td>
                        <td>SAMANTHA SS MRS</td>
                        <td>2 avenue</td>
                        <td>cape town</td>
                        <td>17 Aug 2017</td>
                    </tr>
                    <tr>
                        <td>
                            <div class="ui red ribbon label">202164</div>
                        </td>
                        <td>457575</td>
                        <td>31657</td>
                        <td>5474</td>
                        <td>SAMANTHA SS MRS</td>
                        <td>2 avenue</td>
                        <td>cape town</td>
                        <td>17 Aug 2017</td>
                    </tr>
                    <tr>
                        <td>
                            <div class="ui red ribbon label">202164</div>
                        </td>
                        <td>457575</td>
                        <td>31657</td>
                        <td>5474</td>
                        <td>SAMANTHA SS MRS</td>
                        <td>2 avenue</td>
                        <td>cape town</td>
                        <td>17 Aug 2017</td>
                    </tr>
                    <tr>
                        <td>
                            <div class="ui red ribbon label">202164</div>
                        </td>
                        <td>457575</td>
                        <td>31657</td>
                        <td>5474</td>
                        <td>SAMANTHA SS MRS</td>
                        <td>2 avenue</td>
                        <td>cape town</td>
                        <td>17 Aug 2017</td>
                    </tr>
                    </tbody>
                    <tfoot>
                    <tr>
                        <th colspan="3">
                            <div class="ui right floated pagination menu">
                                <a class="icon item">
                                    <i class="left chevron icon"></i>
                                </a>
                                <a class="item">1</a>
                                <a class="item">2</a>
                                <a class="item">3</a>
                                <a class="item">4</a>
                                <a class="icon item">
                                    <i class="right chevron icon"></i>
                                </a>
                            </div>
                        </th>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
</div>

WebApplication5/Views/Shared/_Layout_Semantic.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
	@Styles.Render("~/Content/css")
    @Styles.Render("~/Content/semantic")
    @Styles.Render("~/Content/calendar")
</head>
<body>
    <div class="ui page grid masthead segment grey">
        <div class="column">
            <div class="inverted secondary pointing ui menu">
                <div class="header item">Digicall</div>
                <div class="right menu">
                    <div class="ui top right pointing mobile dropdown link item">
                        Menu
                        <i class="dropdown icon"></i>
                        <div class="menu">
                            <a class="item">Activities</a>
                            <a class="item">Accounting</a>
                            <a class="item">Setup</a>
                        </div>
                    </div>
                    <div class="ui dropdown link item">
                        System
                        <i class="dropdown icon"></i>
                        <div class="menu">
                            <a class="item" href="@Url.Action("Index", "Claim")">Home</a>
                            <a class="item">Communications</a>
                            <a class="item">Documents</a>
                        </div>
                    </div>
                    <a class="item">Library</a>
                    <a class="item">Community</a>
                    <a class="item" href="@Url.Action("Index", "Search")"><i class="search icon"></i></a>
                </div>
            </div>
            <img src="" class="ui large image" />
            <div class="ui hidden transition information">
                <h1 class="ui inverted header">
                    Digicall Group
                </h1>
                <p></p>
                <div class="large basic inverted animated fade ui button">
                    <div class="visible content">Your Business Needs</div>
                    <div class="hidden content">Now!</div>
                </div>
            </div>
        </div>
    </div>
@RenderBody()
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/semantic")
@RenderSection("scripts", required: false)
</body>
</html>